title: ycb的个人网站
description: 软件工程师 | 全栈开发者 | 开源爱好者
baseurl: ""
url: "https://ssskeyi.github.io"

# 主题设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 社交媒体链接
social_links:
  github: ssskeyi
  email: mailto:3092583301@qq.com

# 导航菜单
header_pages:
  - about.md
  - projects.md
  - blog.md

# 网站设置
timezone: Asia/Shanghai
encoding: utf-8
markdown: kramdown

# 作者信息
author:
  name: ycb
  bio: "热爱技术，专注于全栈开发的软件工程师"